
#define LK_code 0
#define LK_space 1
#define LK_repeat 2
#define LK_l_mar 3
#define LK_t_clr 4
#define LK_delete 5
#define LK_lock 6
#define LK_r_mar 7
#define LK_tab 8
#define LK_mar_rel 9
#define LK_t_set 10
#define LK_shift 11
#define LK_z 12
#define LK_q 13
#define LK_one 14
#define LK_topleft 15
#define LK_a 16
#define LK_x 17
#define LK_w 18
#define LK_two 19
#define LK_s 20
#define LK_c 21
#define LK_e 22
#define LK_three 23
#define LK_d 24
#define LK_b 25
#define LK_v 26
#define LK_t 27
#define LK_r 28
#define LK_four 29
#define LK_five 30
#define LK_f 31
#define LK_g 32
#define LK_n 33
#define LK_m 34
#define LK_y 35
#define LK_u 36
#define LK_seven 37
#define LK_six 38
#define LK_j 39
#define LK_h 40
#define LK_comma 41
#define LK_bracket 42
#define LK_i 43
#define LK_eight 44
#define LK_plus 45
#define LK_k 46
#define LK_period 47
#define LK_o 48
#define LK_nine 49
#define LK_l 50
#define LK_slash 51
#define LK_fraction 52
#define LK_p 53
#define LK_zero 54
#define LK_minus 55
#define LK_semicolon 56
#define LK_quote 57
#define LK_line_space 58
#define LK_return 59
#define LK_paper_down 60
#define LK_paper_up 61
#define LK_backspace 62
#define LK_margin_return 63